name: Pull Request Check

on:
  pull_request:
    types: [ synchronize, opened ]
    branches: [ 'minecraft/*' ]

jobs:
  validate-wrapper:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  initialize:
    needs: validate-wrapper
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-PR${{github.event.number}}-${{ hashFiles('gradle.properties', 'gradle/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-PR${{github.event.number}}-
            ${{ runner.os }}-gradle-${{github.base_ref}}-
            ${{ runner.os }}-gradle-

      - name: Initialize caches
        run: ./gradlew --no-daemon


  license-headers:
    needs: initialize
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Restore gradle cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-PR${{github.event.number}}-${{ hashFiles('gradle.properties', 'gradle/gradle-wrapper.properties') }}

      - name: License headers
        run: ./gradlew checkLicenses --no-daemon

  build:
    needs: initialize
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Restore gradle cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-PR${{github.event.number}}-${{ hashFiles('gradle.properties', 'gradle/gradle-wrapper.properties') }}

      - name: Build
        run: ./gradlew build -x checkLicenses --no-daemon

      - name: Cache build output
        uses: actions/cache/save@v3
        with:
          path: |
            .gradle/
            !.gradle/loom-cache
            build/
          key: ${{ runner.os }}-build-PR${{github.event.number}}-${{ github.sha }}

  analysis:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Restore gradle cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-PR${{github.event.number}}-${{ hashFiles('gradle.properties', 'gradle/gradle-wrapper.properties') }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          debug: true

      - name: Build
        run: ./gradlew build -x checkLicenses --no-daemon

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  test:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Restore gradle cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-PR${{github.event.number}}-${{ hashFiles('gradle.properties', 'gradle/gradle-wrapper.properties') }}

      - name: Restore cached build output
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            .gradle/
            !.gradle/loom-cache
            build/
          key: ${{ runner.os }}-build-PR${{github.event.number}}-${{ github.sha }}

      - name: Test
        run: ./gradlew test --no-daemon

  gametest:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Restore gradle cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-PR${{github.event.number}}-${{ hashFiles('gradle.properties', 'gradle/gradle-wrapper.properties') }}

      - name: Restore cached build output
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            .gradle/
            !.gradle/loom-cache
            build/
          key: ${{ runner.os }}-build-PR${{github.event.number}}-${{ github.sha }}

      - name: Gametest
        run: ./gradlew runGametest --no-daemon
