name: Maven Publish

on:
  push:
    branches:
      - minecraft/*

jobs:
  Publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          SNAPSHOT: true
          PRE_RELEASE: false
          NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_SNAPSHOT_URL }}
          BUILD_NUMBER: ${{ github.run_id }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
